# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapping.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mapping(object):
    def setupUi(self, Mapping):
        Mapping.setObjectName("Mapping")
        Mapping.resize(782, 581)
        Mapping.setMinimumSize(QtCore.QSize(782, 581))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Mapping)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(Mapping)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setStyleSheet("border-left: 2px solid rgb(170, 85, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setStyleSheet("border-left: 1px solid rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("border-top-color: rgb(0, 0, 0);\n"
"border-top-width: 2px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_showPertHermite = QtWidgets.QPushButton(self.frame_2)
        self.button_showPertHermite.setObjectName("button_showPertHermite")
        self.horizontalLayout_4.addWidget(self.button_showPertHermite)
        self.button_showMapHermite = QtWidgets.QPushButton(self.frame_2)
        self.button_showMapHermite.setObjectName("button_showMapHermite")
        self.horizontalLayout_4.addWidget(self.button_showMapHermite)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.check_mapRegen = QtWidgets.QCheckBox(self.frame_3)
        self.check_mapRegen.setObjectName("check_mapRegen")
        self.horizontalLayout_5.addWidget(self.check_mapRegen)
        self.lineEdit_editMapp = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_editMapp.setObjectName("lineEdit_editMapp")
        self.horizontalLayout_5.addWidget(self.lineEdit_editMapp)
        self.button_browse_map = QtWidgets.QPushButton(self.frame_3)
        self.button_browse_map.setObjectName("button_browse_map")
        self.horizontalLayout_5.addWidget(self.button_browse_map)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.button_mapRegen = QtWidgets.QPushButton(self.frame_3)
        self.button_mapRegen.setObjectName("button_mapRegen")
        self.verticalLayout_3.addWidget(self.button_mapRegen)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Mapping)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/ArrowDouble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 18)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.button_next_pertGraph = QtWidgets.QPushButton(Mapping)
        self.button_next_pertGraph.setObjectName("button_next_pertGraph")
        self.verticalLayout_4.addWidget(self.button_next_pertGraph)

        self.retranslateUi(Mapping)
        QtCore.QMetaObject.connectSlotsByName(Mapping)

    def retranslateUi(self, Mapping):
        _translate = QtCore.QCoreApplication.translate
        Mapping.setWindowTitle(_translate("Mapping", "Form"))
        self.label.setText(_translate("Mapping", "Mapping"))
        self.label_4.setText(_translate("Mapping", "Ligand A"))
        self.label_6.setText(_translate("Mapping", "Ligand B"))
        self.label_7.setText(_translate("Mapping", "Perturbation State A"))
        self.label_8.setText(_translate("Mapping", "Perturbation State B"))
        self.label_10.setText(_translate("Mapping", "Highlight"))
        self.comboBox.setItemText(0, _translate("Mapping", "Mutation"))
        self.button_showPertHermite.setText(_translate("Mapping", "Show Pert in Hermite"))
        self.button_showMapHermite.setText(_translate("Mapping", "Show mapping in Hermite"))
        self.label_12.setText(_translate("Mapping", "Ragen Mapping"))
        self.check_mapRegen.setText(_translate("Mapping", "Manuing Mapping"))
        self.button_browse_map.setText(_translate("Mapping", "Browse"))
        self.button_mapRegen.setText(_translate("Mapping", "Regen"))
        self.label_11.setText(_translate("Mapping", "Pairs"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Mapping", "Ligand A"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Mapping", "Ligand B"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Mapping", "sim. score"))
        self.button_next_pertGraph.setText(_translate("Mapping", "Confirm Mapping & go to set parameters"))

