# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perturbation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Perturbation(object):
    def setupUi(self, Perturbation):
        Perturbation.setObjectName("Perturbation")
        Perturbation.resize(829, 534)
        self.verticalLayout = QtWidgets.QVBoxLayout(Perturbation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Perturbation)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_pert = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_pert.setTabBarAutoHide(False)
        self.tabWidget_pert.setObjectName("tabWidget_pert")
        self.tab_ligs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ligs.sizePolicy().hasHeightForWidth())
        self.tab_ligs.setSizePolicy(sizePolicy)
        self.tab_ligs.setObjectName("tab_ligs")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_ligs)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.tab_ligs)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_ligands = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_ligands.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_ligands.setWordWrap(True)
        self.tableWidget_ligands.setObjectName("tableWidget_ligands")
        self.tableWidget_ligands.setColumnCount(4)
        self.tableWidget_ligands.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ligands.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ligands.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ligands.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ligands.setHorizontalHeaderItem(3, item)
        self.tableWidget_ligands.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_ligands.horizontalHeader().setHighlightSections(True)
        self.tableWidget_ligands.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_ligands.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ligands.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_3.addWidget(self.tableWidget_ligands)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.button_graphLoad = QtWidgets.QPushButton(self.widget_2)
        self.button_graphLoad.setObjectName("button_graphLoad")
        self.horizontalLayout_2.addWidget(self.button_graphLoad)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.setWeightLabel = QtWidgets.QLabel(self.widget)
        self.setWeightLabel.setObjectName("setWeightLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setWeightLabel)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.similarityMethodsLabel = QtWidgets.QLabel(self.widget)
        self.similarityMethodsLabel.setObjectName("similarityMethodsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.similarityMethodsLabel)
        self.similarity_method = QtWidgets.QComboBox(self.widget)
        self.similarity_method.setObjectName("similarity_method")
        self.similarity_method.addItem("")
        self.similarity_method.addItem("")
        self.similarity_method.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.similarity_method)
        self.optimalCriteriaLabel = QtWidgets.QLabel(self.widget)
        self.optimalCriteriaLabel.setObjectName("optimalCriteriaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.optimalCriteriaLabel)
        self.optimal_criteria = QtWidgets.QComboBox(self.widget)
        self.optimal_criteria.setObjectName("optimal_criteria")
        self.optimal_criteria.addItem("")
        self.optimal_criteria.addItem("")
        self.optimal_criteria.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.optimal_criteria)
        self.numberOfCycleLabel = QtWidgets.QLabel(self.widget)
        self.numberOfCycleLabel.setObjectName("numberOfCycleLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.numberOfCycleLabel)
        self.number_of_cycles = QtWidgets.QSpinBox(self.widget)
        self.number_of_cycles.setObjectName("number_of_cycles")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.number_of_cycles)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.button_graphGen = QtWidgets.QPushButton(self.widget)
        self.button_graphGen.setObjectName("button_graphGen")
        self.verticalLayout_3.addWidget(self.button_graphGen)
        self.verticalLayout_6.addWidget(self.widget)
        self.tabWidget_pert.addTab(self.tab_ligs, "")
        self.tab_pairs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pairs.sizePolicy().hasHeightForWidth())
        self.tab_pairs.setSizePolicy(sizePolicy)
        self.tab_pairs.setObjectName("tab_pairs")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_pairs)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_pairs = QtWidgets.QTableWidget(self.tab_pairs)
        self.tableWidget_pairs.setObjectName("tableWidget_pairs")
        self.tableWidget_pairs.setColumnCount(4)
        self.tableWidget_pairs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pairs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pairs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/ArrowDouble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.tableWidget_pairs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pairs.setHorizontalHeaderItem(3, item)
        self.tableWidget_pairs.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_5.addWidget(self.tableWidget_pairs)
        self.tabWidget_pert.addTab(self.tab_pairs, "")
        self.verticalLayout_2.addWidget(self.tabWidget_pert)
        self.horizontalLayout.addWidget(self.frame)
        self.graph_frame = QtWidgets.QFrame(Perturbation)
        self.graph_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph_frame.setObjectName("graph_frame")
        self.graph_layout = QtWidgets.QVBoxLayout(self.graph_frame)
        self.graph_layout.setObjectName("graph_layout")
        self.label_4 = QtWidgets.QLabel(self.graph_frame)
        self.label_4.setObjectName("label_4")
        self.graph_layout.addWidget(self.label_4)
        self.button_row = QtWidgets.QHBoxLayout()
        self.button_row.setObjectName("button_row")
        self.button_graphRedo = QtWidgets.QPushButton(self.graph_frame)
        self.button_graphRedo.setObjectName("button_graphRedo")
        self.button_row.addWidget(self.button_graphRedo)
        self.button_graphUndo = QtWidgets.QPushButton(self.graph_frame)
        self.button_graphUndo.setObjectName("button_graphUndo")
        self.button_row.addWidget(self.button_graphUndo)
        self.button_graphAddEdge = QtWidgets.QPushButton(self.graph_frame)
        self.button_graphAddEdge.setObjectName("button_graphAddEdge")
        self.button_row.addWidget(self.button_graphAddEdge)
        self.button_graphDelEdge = QtWidgets.QPushButton(self.graph_frame)
        self.button_graphDelEdge.setObjectName("button_graphDelEdge")
        self.button_row.addWidget(self.button_graphDelEdge)
        self.graph_layout.addLayout(self.button_row)
        self.horizontalLayout.addWidget(self.graph_frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_next_pert = QtWidgets.QPushButton(Perturbation)
        self.button_next_pert.setObjectName("button_next_pert")
        self.verticalLayout.addWidget(self.button_next_pert)

        self.retranslateUi(Perturbation)
        self.tabWidget_pert.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Perturbation)

    def retranslateUi(self, Perturbation):
        _translate = QtCore.QCoreApplication.translate
        Perturbation.setWindowTitle(_translate("Perturbation", "Form"))
        self.tableWidget_ligands.setSortingEnabled(True)
        item = self.tableWidget_ligands.horizontalHeaderItem(0)
        item.setText(_translate("Perturbation", "Name"))
        item = self.tableWidget_ligands.horizontalHeaderItem(1)
        item.setText(_translate("Perturbation", "Exp. Affinity\n"
" (kcal/mol)"))
        item = self.tableWidget_ligands.horizontalHeaderItem(2)
        item.setText(_translate("Perturbation", "Exp. Error\n"
"(kcal/mol)"))
        item = self.tableWidget_ligands.horizontalHeaderItem(3)
        item.setText(_translate("Perturbation", "Weight"))
        self.label_2.setText(_translate("Perturbation", "Build Perturbation Graph"))
        self.radioButton.setText(_translate("Perturbation", "Loading  Perburtaion Graph"))
        self.label.setText(_translate("Perturbation", "Graph File"))
        self.button_graphLoad.setText(_translate("Perturbation", "Browse"))
        self.radioButton_2.setText(_translate("Perturbation", "Generate  Perburtaion Graph"))
        self.setWeightLabel.setText(_translate("Perturbation", "Set Weights"))
        self.label_3.setText(_translate("Perturbation", "Please set on the above table"))
        self.similarityMethodsLabel.setText(_translate("Perturbation", "Similarity Methods"))
        self.similarity_method.setItemText(0, _translate("Perturbation", "Tanimoto fingerprint"))
        self.similarity_method.setItemText(1, _translate("Perturbation", "MACCS fingerprint"))
        self.similarity_method.setItemText(2, _translate("Perturbation", "Common Substructure"))
        self.optimalCriteriaLabel.setText(_translate("Perturbation", "Optimal criteria"))
        self.optimal_criteria.setItemText(0, _translate("Perturbation", "A-optimal"))
        self.optimal_criteria.setItemText(1, _translate("Perturbation", "G-optimal"))
        self.optimal_criteria.setItemText(2, _translate("Perturbation", "D-optimal"))
        self.numberOfCycleLabel.setText(_translate("Perturbation", "Number of cycle"))
        self.button_graphGen.setText(_translate("Perturbation", "Build Perturbation Graph"))
        self.tabWidget_pert.setTabText(self.tabWidget_pert.indexOf(self.tab_ligs), _translate("Perturbation", "Ligands"))
        item = self.tableWidget_pairs.horizontalHeaderItem(0)
        item.setText(_translate("Perturbation", "Ligand A"))
        item = self.tableWidget_pairs.horizontalHeaderItem(1)
        item.setText(_translate("Perturbation", "Ligand B"))
        item = self.tableWidget_pairs.horizontalHeaderItem(2)
        item.setText(_translate("Perturbation", "sim. score"))
        item = self.tableWidget_pairs.horizontalHeaderItem(3)
        item.setText(_translate("Perturbation", "Ops"))
        self.tabWidget_pert.setTabText(self.tabWidget_pert.indexOf(self.tab_pairs), _translate("Perturbation", "Pairs"))
        self.label_4.setText(_translate("Perturbation", "Perturbation Graph"))
        self.button_graphRedo.setText(_translate("Perturbation", "Redo"))
        self.button_graphUndo.setText(_translate("Perturbation", "Undo"))
        self.button_graphAddEdge.setText(_translate("Perturbation", "Add Edge"))
        self.button_graphDelEdge.setText(_translate("Perturbation", "Delete Edge"))
        self.button_next_pert.setText(_translate("Perturbation", "Confirm Pertubation Graph & Go to Check Mapping "))

